language: python
dist: xenial
python:
  - "3.7"
  - "3.8"

install:
  - pip install codecov
  - pip install -e ".[test, typecheck]"

script:
  - make -i typecheck
  - make test

after_success:
  - codecov
